### ISSUE TITLE
Original (on-wake from SD is not loaded) --> After more testing (on-wake from SD is "only useful" on cold boots)

### ISSUE THREAD

**Issue by arspr** [ottokiksmaler/nx500_nx1_modding#54]
Ooops guys. I've double, triple and quadruple checked and I think there's something QUITE wrong here.

I'm on nx-on-wake + nx-patch 5.0 on my NX1.

But I wanted to test the SD override over the nx-patch so I've copied nx-on-wake folder from the nx-on-wake mod to an extra SD I have (with mp3 music for my car).

Well, this second SD card DOES NOT usually block the nx-patch mod. I can access nx-patch GUI  through OK+OK. Sometimes it works as expected, and I cannot access it, but most times it does not.

I've tested ten thousand times:
+ Powering the camera WITHOUT SD. OK+OK always shows the nx-patch GUI.
+ Powering the camera with my main SD card (no nx-on-wake folder in it). OK+OK always shows the nx-patch GUI.
+ Powering the camera with my second music SD card (with the nx-on-wake folder and blocking on-wake file; and now also a DCIM folder too). Most of the times OK+OK continues showing nx-patch GUI.

**Comment by arspr** [comment]
Just to make it easier.

BOTH nx-patch and the nx-on-wake dummy "satellite" mod use a triple blinking. So it's "impossible" to quickly distinguish which mod is actually being loaded looking at the LED.

Opening the "dummy" on-wake file from nx-on-wake mod I *think* I can easily understand it. Could you confirm that if I delete lines 11 to 14 I should get only a DOUBLE blinking instead of a triple one?

(Also I see a blank 15 line in Notepad++. Is that line strictly needed?)

(This could be an easier way to test which "satellite" mod is being loaded).

**Comment by ottokiksmaler** [comment]
Or you could leave single longer blink. Also test what halogens when the camera goes to sleep and then wakes up. I had to put a delay in my programs when working with SD card as it's not immediately available.

**Comment by arspr** [comment]
Hey, I *think* I've discovered what happens...

**nx-patch is only killed AFTER A COLD BOOT (battery out/in cycle).**

I explain myself. I start with my normal SD and everything working fine (OK+OK launches nx-patch GUI as expected, of course).

- If I power the camera off, I swap SD cards so I put the "on-wake" one, and then I power the camera on. I can still access nx-patch GUI through OK+OK.

- But I take the battery out. And then I put it in and then I power the camera on, I cannot access nx-patch GUI through OK+OK any more.

- If now I power the camera off, swap SD cards again (so my normal no "on-wake" one is again inside), and I power the camera on, I can again access nx-patch GUI through OK+OK.

So, I'm no expert, but it really seems, once nx-patch has been loaded into memory, it always remains in it. It doesn't matter if you try to kill it through the SD on-wake dummy mod. You can only kill it, TAKING THE BATTERY OUT, and then preventing it from being loaded through the SD on-wake dummy mod.

Is this the expected behaviour? If that is the case, I really think you should change the readme file for nx-on-wake. I expected that I could kill any internal mod through a dummy SD on-wake. But this only happens on cold boots, not on warm ones.

**Comment by ottokiksmaler** [comment]
That's how keyscan from Bluetooth mods operate - once it's loaded until you do full reboot via battery removal it's active and running. Fit example, you can turn Bluetooth off and power the camera off and on and it's still there. Same thing applies to any program run from internal filesystem (anything fun from the SD card is killed on power off regardless of the battery).

**Comment by vasile-gh** [comment]
@arspr ok I understand. Well, it is a _feature_ not a _bug_ :-). You simply copied on SD card a mod designed to sit inside the camera. 
The mod was not designed for this and does not support manual placement on the card. Hence the unexpected (to you)  behaviour.

But there is another angle here: what happens when there's a "resident" keyscan launched by a camera-based mod and a new mod is put in through sd card.

The nx-on-wake does NOT (no way to do that without knowing what every mod does) guarantee that a card-based mod annuls completely the camera-based mods.
It ONLY guarantees that it won't run the camera-based mod launcher. If there are already running SD card mods, it won't kill the memory-resident ones.

And since memory-resident parts are killed on battery pull, then the card-based mods will execute correctly.

So the nx-on-wake README is still correct. But I will replace "override" which you interpreted in a way I did not intend to, with "**you can always kill misbehaving satellite camera-resident mods by a simple file stored on the SD card.**"

This is what I really meant when I wrote that part.

**Comment by vasile-gh** [comment]
correct :-)

**Comment by arspr** [comment]
I really think some further clarification should be done.

I start copying from the nx-on-wake README, putting the important misleading parts in bold font.

/Start of README copy/

   The mod will ensure that every time the camera is started (cold **or warm**,
   i.e. with or without battery pull), the camera will:
     (a) if there's a file on the SD card named /nx-on-wake/on-wake, it will
         attempt to run it (and only it - nothing else). [...]
     (b) **ONLY if there's NO on-wake file on the SD card**, the mod will try
         to run a file called /opt/usr/nx-on-wake/on-wake. [...]
    [...]

   It also ensures that you have a back-out procedure in case a camera-resident
   mod misbehaves: **you can always override satellite camera-resident mods by a
   simple file stored on the SD card**.
   
   This mod comes with a **very simple "blink three times" SD-card satellite mod**
   that serves as demo AND **can be used to disable any camera-resident
   misbehaving mods**. [...]

>>>>>

/End of README copy/

Well, just reading it I get the impression if I want to kill nx-patch (installed internally so I suppose installed in whichever /opt/usr/ is), because suppose it's misbehaving, I only have to copy that dumb "blink-three-times" mod because you mention it will work ALWAYS in cold or warm boots. But the real situation is that unless I do an extra cold boot, there can be rests of the misbehaving mod living in the memory...

Because of that I would add a warning right after where you say I can use the "blink three times" mod as a life-saver, (in the >>>> position), saying something like:

_ATTENTION. Although the "blink three times" mod installation in your SD will efectively prevent the misbehaving installed mod from being loaded no matter if you do cold (batery out cycle) o warm (only power off cycle) boots, till you perform a cold boot, that misbehaving installed mod could be still alive in the camera memory. 
Short story: if you want to use "blink three times" as a life-saver in the SD card, perform a battery out/in cycle to be sure that whichever mod you have previously installed is fully killed._

**Comment by ottokiksmaler** [comment]
FWIW, running ```reboot``` does full reboot (like battery removal).

**Comment by arspr** [comment]
Just for learning.

I suppose [this issue](http://www.dpreview.com/forums/post/57931139) about not being able to access mod menu (I've also suffered it) is also related to this, isn't it?

I mean, I suppose, there's "rubbish" in the memory from v.5.01 and therefore till you do a full cold boot (removing everything from memory) v5.1 does not properly work. Am I right?

**Comment by vasile-gh** [comment]
yes. I was incorrectly cleaning up before install. Fixed now in v5.03 (to be uploaded very shortly).

**Comment by arspr** [comment]
He, he,

I've just read your v1.03 nx-on-wake readme and I think you typed it quite fast (and quite needed of sleep?). Re-read the added paragraph: a duplicated "misbehaving" and some verb/subject missing...

BTW: Thanks for the mention. It wasn't needed at all. The work is actually yours.

**Comment by vasile-gh** [comment]
yes :-(. I don't usually get to work on this before 10-11pm during the week.

**Comment by arspr** [comment]
@Vasile: You are going to hate me buuuut... you still have a duplicated "misbehaving" in nx-on-wake readme v1.04

**Comment by vasile-gh** [comment]
@arspr $&^%$&^%$&!@#. OK

**Comment by arspr** [comment]
@Vasile: Nevertheless, quite possibly the MOST serious issue the readme has is xnilo's one about M.

As a side info: I haven't located the exact trigger but sometimes the PASM dial doesn't work fine with your mod and even with Kino's one, (and even with just Samsung stock software?):

- I've detected for sure PASM dial doesn't work if the nx-patch GUI (or nx-ks one) is displayed. I posted it in this [old bug](https://github.com/ottokiksmaler/nx500_nx1_modding/issues/45) (second post).
- And sometimes, the PASM mode is wrong or it lags. Specially **A** tends to fail more than others, (or maybe it's I usually shoot in **A**). _And this is the maybe related part, when this happens, quite usually **the camera seems to default to M**_.

So maybe **M** is special (no signal, no variable, no something) and as a side effect it triggers xnilo's trouble. I think this is work for your burner camera... (I'm not going to try re-flashing my NX1 in order to confirm a bug in the hibernation image...)

**Comment by vasile-gh** [comment]
@arspr 
1. I could not reproduce xnilo's issue on my camera - I am groping in the dark there but I thought I better cover all bases - the Auto requirement cannot hurt, so I thought I'd put it there although I do not think it will change anything.
2. Indeed, mod_gui can interfere with the camera operation while its UI is displayed. It is just the way it works, and I think only @ottokiksmaler can help there. It would be good if you could find reproducible instances where this happens on genuine firmware - never happened to me.
3. If you read the mod source code you will see that it does not interfere **at all** with the camera - @ottokiksmaler can you also take a look and give me your thoughts. That was indeed the idea:  to just have it there, doing nothing while the camera operates, only doing something upon boot/wakeup.

**Comment by ottokiksmaler** [comment]
I have a bad feeling that his problems are of hardware nature - Samsung nx cameras have a long and sorry history of failing mode dial (my nx1000 sometimes switches on its own and most often in A, there are numerous user reports even in dpreview.com forums). The only solution is service and replacement of top plate. 
It seems they haven't fixed it even in the latest models :(

**Comment by Chopperguy** [comment]
Hi Vasile, Otto & beta testers
 
just started installing the new mod to my nx500

stupidly my eyes jumped a line when reading and I pulled the battery after the 10 second mark not the 5 minute mark,

the camera is still on,
would you have any recommendation, 
ie keep going with the readme,
or turn off and reflash firmware ?

i feel like a blind tit

**Comment by Chopperguy** [comment]
not bricked.

**Comment by vasile-gh** [comment]
@Chopperguy How's it going

**Comment by Chopperguy** [comment]
No, I re installed the mod before I got your message, 
seems ok,  nx patch installed.
will re flash firmware if you think I should.

**Comment by arspr** [comment]
@ottokiksmaler: about the issues with the PASM dial.
In fact [I suffered one](http://www.dpreview.com/forums/post/55963654) with my NX1 a year ago (at the beginning I thought it was a bad FW update). But right now my "new" and "infrequent" issues with it are much less severe.
Because of that I do think it's something purely on the software side and because of that I thought it might be related to xnilo issue... but maybe I'm wrong and my PASM dial is on the verge of breaking down again... (I hope not).

**Comment by ottokiksmaler** [comment]
Hope not too, I'm trying to upload new version of mod_gui that passes PASM changes to camera but github is falling in "Processing your files… This may take a few minutes to complete" endless loop (have no idea why).

here it is
https://github.com/ottokiksmaler/nx500_nx1_modding/commit/53961aaed98f2638bb1f95470bbe9a58229dbdb3

**Comment by arspr** [comment]
@ottokiksmaler: I'm no coder so please use my comments with caution (throw them to the dustbin?). I've seen some strange things in that file:

- The NX1 PASM dial is P A S M C1 C2 smart auto. But your code "seems" to have just one custom mode and no mention to Auto.
- OTOH the white (I suppose unchanged old) lines "seem" to include power off. Well, I can confirm that my NX1 on nx-patch v5.2 doesn't turn off if the mod GUI is displayed...

**Comment by ottokiksmaler** [comment]
I don't think Vasile is using bleeding edge releases in his mod pack. That said I have to do two things - make some sort of testing tool that enables running test programs from SD card and how to collect output (or someone with NX1 that can use telnet).

**Comment by arspr** [comment]
If you post a THOROUGH guide I volunteer to feed you with that Telnet info. But I do not even know what Telnet is... (so you can evaluate my LOW starting point...).

Also, I'm on Windows 10, in case a PC with Linux is also required...

**Comment by ottokiksmaler** [comment]
How to use telnet to debug:
1. Put required program on SD card (for example save https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/mod_gui/mod_gui?raw=true as "mod_gui" and copy it to SD card on your PC)
2. Put SD card in the camera
3. Start the camera
4. Start WiFi on camera (for example from pull down menu or from normal menu) and connect to the same WiFi network your PC is connected
5. start Vasile's GUI and select "telnet" from the menu
6. It should now display IP address of your camera - write it down (or memorize, it will be different only in last number from your PC, for example if PC is 192.168.1.56 camera will be 192.168.1.73 or similar)
7. Start  telnet on PC - either by opening command prompt and typing "telnet 192.168.1.73" (with correct IP address) or from some GUI program like PuTTY (http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html)
8. You will see login prompt, enter "root" as username, you will not be asked for password
9. From there you should have access to command line interface of your camera and be able to execute anything you want.
10. Try executing "/mnt/mmc/mod_gui  /opt/usr/nx-on-wake/main debug" and watch the output. This will display you the normal GUI menu you expect. Now, when you click anything the program should print the key code and exit (like "Key: F6")
11. You now have to restart it with "/mnt/mmc/mod_gui  /opt/usr/nx-on-wake/main debug" again for another key. You should test what happens when you switch to C1, C2 and Power-Off (as I don't have C1 and C2 key and power off works for me).

Same thing applies to other tools you would like to test, new versions of focus_stacking, etc.
If you need further assistance don't hesitate to ask.

**Comment by arspr** [comment]
Ok, I think it's very comprehensive. I'll test ASAP.

Just one doubt. How do I install your "new" versions? Or do I just test against the normally installed nx-patch version whatever (5.2 at the moment)?

**Comment by vasile-gh** [comment]
@arspr: before running the test you do:
```killall keyscan; rm /tmp/keyscan.pid```
This will allow you to run keyscan in debug mode as @ottokiksmaler indicated.
After you are done you should run:
```/opt/usr/nx-on-wake/on-wake```
This will restart the mod making it available "as usual.

This will work (for now) regardless of mod version.

**Comment by arspr** [comment]
Firstly I post, the info I get with telnet similar to ottokiksmaler in case it's helpful.

```
[root@drime5 ~]# /mnt/mmc/mod_gui /opt/usr/nx-on-wake/main debug
Scripts:/opt/usr/nx-on-wake/    Configuration file:main
Configuration file: /opt/usr/nx-on-wake/main.NX1
Model: NX1
Release: 1.41
Running MOD_GUI
CONFIG: resolutions     @/tmp/resolutions.NX1
CONFIG: focus stacking  /opt/usr/nx-on-wake/focus_stack
CONFIG: bit rates       @/opt/usr/nx-on-wake/bitrates.NX1
CONFIG:         (null)
CONFIG: make default    /bin/cp /tmp/initial_patches.sh /opt/usr/nx-on-wake/
CONFIG: telnet  telnet.sh
CONFIG: about v5.2      /opt/usr/nx-on-wake/about.sh
CONFIG: uninstall       /opt/usr/nx-on-wake/uninstall.sh
Auto execute: /opt/usr/nx-on-wake//auto/telnet.sh
Debug ON
```

Now, I post every single key I have on the camera **BUT power on**, because when I do power off with [that file](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/mod_gui/mod_gui?raw=true) in my SD the camera powers off...

Auto > P: F7
P > A: F8
A > S: F9
S > M: F10
M > C1: KP_Home
C1 > C2: Scroll_Lock
C2 > Smart: F4
Smart > Auto: F6
(When I reverse it's the same ie Auto > Smart: F4 too).

Power Off: XF86PowerOff (and the camera has powered off)
EV: XF86WWW
Top LCD Light: XFLaunch2
Rec: XF86WebCam
AEL: XF86Favorites
Rear WiFi button: XF86Mail
AF ON: XF86Launch9
Menu: Menu
Fn: XF86HomePage
Disp (Up): KP_Up
Right: KP_Right
Left: KP_Left
Down: KP_Down
OK: KP_Enter
Play: XF86Tools
Delete: KP_Delete
EVF: XF86DOS
AF: XF86TaskPane
ISO: XF86Launch7
Metering zone: Hiragana_Katakana
WB: XF86Launch6

Single > Continuous normal: Hiragana
Continuous normal > Cont. High: Muhenkan
Continuous High > Temporized: Control_R
Temporized > BKT: Alt_R
...Reversed
Continuous normal > Single: Katakana

Half-Shutter: Super_L
Full-Shutter (I mean I push shutter completely on the very same movement): Super_L (It seems I cannot jump over Half-Shutter)

Front Preview button: XF86TouchpadOff

Flash: (Nothing, confirmed it's just a physical release only)

Lens keys -16-50S- (iFn, AF<->MF, OIS ON<->OFF): (Nothing)

Upper command wheel right: XF86ScrollUp
Upper command wheel left: XF86ScrollDown

Rear command wheel right: XF86AudioNext
Rear command wheel left: XF86AudioPrev

Rear wheel (around Up-Right-Down-Left keys) clockwise: Right
Rear wheel counterclockwise: Left

**Comment by arspr** [comment]
BTW. telnet does not work from Windows CMD. It says "unrecognised command"... ?!?!?!

**Comment by ottokiksmaler** [comment]
Thank you, that's exactly what I needed. It also means that the  current version of mod_gui powers the camera off correctly.

**Comment by arspr** [comment]
You're welcome.

If I can help you coders somehow, just ask for it. (I'll ask for features myself... cof, cof, cof, either BBAF or bug-free AFL maybe? ;-p )

**Comment by vasile-gh** [comment]
BTW @arspr if you prefix the cut/paste output with triple back quote camera text output will look a lot nicer: like this:
```
blah
```

**Comment by arspr** [comment]
(I'm closing this. I think it's fully covered in readme and the key log is going to remain available)
