### ISSUE TITLE
nx-patch v5.1x issues

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#58]

**Comment by ottokiksmaler** [comment]
[ ]  Add "reboot" at the end of install of patch - this will ensure the camera is fully rebooted and using the current version.

**Comment by vasile-gh** [comment]
@ottokiksmaler  no need for reboot I just did not completely clean previous version. Fixed and version bumped.

**Comment by arspr** [comment]
Well, two (three) issues with otto's focus stack:

- The one [Hirsti posted](http://www.dpreview.com/forums/post/57931139) about the camera finishing in a "silent" and "hidden" MF mode.
- I think focus stack is supposed to display a "Focus stack in progress" message or something like that (it was a request accepted by otto, made when NX-KS). And I think otto k said it was present in v2.0 of focus stack mod. Well, if it is there I can confirm it doesn't show up in my NX1.
- A small cosmetic fix. If you display the focus distance bar while taking the focus stack pictures (through Disp cycle till you get it, in S lenses only AFAIK), it shows your _previous_ frame distance. (This issue also affected the saved focus mod present in NX-KS too. If you jumped to a saved position the distance indicator was NOT updated. A small touch in the focus ring, if you were in MF, fixed that mismatch. In case this info is useful to track the issue down).

**Comment by arspr** [comment]
@ottokiksmaler: two other small (well, minimal) issues with focus stack configuration screen:

- Frames has room for only a two figure number. And [in this blog linked by ttbek](http://blog.patdavid.net/2013/01/focus-stacking-macro-photos-enfuse.html) they speak that sometimes they do even 100+ stacks... (It's just cosmetic because if you type 100 the number is just displayed in two lines. Ugly, but only ugly).
- With a 2+ figure number let's say 15, the pointer is always set after the first figure (in this case 1). So if I want to type 23 I cannot just "delete and type", I have to "touch till you move the pointer after the last figure and then delete and type". Pointer should be automatically placed after the last figure if possible.

**Comment by arspr** [comment]
@ottikiksmaler: and now a feature request for your focus stack feature: **A locking white balance option** (if possible).

I explain. Right now, when you do a focus stack, you are actually taking n different and independent pictures, so in each one the camera decides the shooting parameters. So at the end you can have pictures with _**different**_ exposure parameters. And this can be good or bad...

If I want to lock shutter time, aperture, ISO, it's quite easy nevertheless as you can imagine. But locking WB is quite trickier. Sure I can use a predefined value or even a user setting, but what I would normally want is the camera evaluating AWB and then _**not changing it**_ through the focus stack process. I mean, all the pictures taken with the first picture WB value.

Therefore: is it possible to lock this first picture WB value through all the stack process? (And always as an option, locking exposure parameters can be good or bad depending on each shooting situation).

_(If it's not possible or if it's really difficult, I can always normalize them in Lightroom as I shoot in Raw, this option would be specially interesting for people shooting in JPG)._

**Comment by ottokiksmaler** [comment]
If you leave it in AWB it will evaluate every game independently. For it to be fixed it would have to be set somehow - it might be possible by taking a first photo, reading temperature and then setting it for other frames but this is just an idea, I would have to see if it's feasible. 
When I do lapses or similar I very much prefer using custom wb from normal shooting menu.

**Comment by ottokiksmaler** [comment]
OK, updated version (2.10) uploaded (https://github.com/ottokiksmaler/nx500_nx1_modding/commit/98f8f2f8d4ecc5f915872b638d11d5797dcac7a0) with following fixes:
- Restores AF mode on ending stacking (tested on NX500, need testers on NX1)
- Fixed a bit UI with entry of number of frames and delay

I have no ide why it doesn't display notices like "Makin 10 photos ..." and "#1 of 10" - it works on my camera, it should on other cameras but EFL toolkit is very funky on these cameras - it's very difficult to find out without replicating the issue.

**Comment by ottokiksmaler** [comment]
@arspr V2.20 here https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/focus_stack?raw=true if you want to test, "Enter" key from touch keyboard does the same as click on "OK"

**Comment by arspr** [comment]
Do I suppose I load it with the "similar" telnet trick I've used with mod_gui? (adapting the command)

**Comment by ottokiksmaler** [comment]
Yes, that way you can run almost anything we publish here.

**Comment by arspr** [comment]
Let's start:

- Prettier configuration dialogue: FIXED.

- Pointer at the right side of the number: FIXED.

- OK as Enter. At least in my NX1 it doesn't work:
```
[root@drime5 ~]# /mnt/mmc/focus_stack
Reading configuration... 100 1
Stacking with 100 photos at 1 delay and 60 button height
elm_cnp.c: Adding drop target calls xwin=0x1e00008
Key: BackSpace
Key: BackSpace
Key: BackSpace
Key: 5
Key: KP_Enter
Key: KP_Enter
Key: KP_Enter
Key: KP_Enter
Key: KP_Enter
Key: KP_Enter

```

- AF returned at the end of the stack: it seems FIXED (but I'll do more tests from SAF/CAF, different area modes, et cetera).
- Progress message: NOT fixed. In case it's useful I post the full results from that stacking (5 pictures - 1 s):

```
Stacking - Near: 1663   Far: 1459       Photos: 5       Delay: 1
Current focus mode: 0x70000 (458752)
CMD: /usr/bin/st app nx capture af-mode manual

CMD: /usr/bin/st cap capdtm setusr AFMODE 0x70003

UserData is set
Current focus position: 1424
CMD: /usr/bin/st cap iq af mv 255 239 255
cur_pos 1424 tar_pos 1663
Current focus position: 1664
far: 1459 current: 1664 delta: -51.250000
CMD: /usr/bin/st key push s1 && /bin/sleep 0.3 && /usr/bin/st key click s2 && /usr/bin/st key release s1 && /bin/sleep 0.5 && /usr/bin/st key click s1
CMD: /usr/bin/st cap iq af mv 255 -52 255
cur_pos 1664 tar_pos 1612
CMD: /usr/bin/st key push s1 && /bin/sleep 0.3 && /usr/bin/st key click s2 && /usr/bin/st key release s1 && /bin/sleep 0.5 && /usr/bin/st key click s1
CMD: /usr/bin/st cap iq af mv 255 -51 255
cur_pos 1611 tar_pos 1560
CMD: /usr/bin/st key push s1 && /bin/sleep 0.3 && /usr/bin/st key click s2 && /usr/bin/st key release s1 && /bin/sleep 0.5 && /usr/bin/st key click s1
CMD: /usr/bin/st cap iq af mv 255 -51 255
cur_pos 1559 tar_pos 1508
CMD: /usr/bin/st key push s1 && /bin/sleep 0.3 && /usr/bin/st key click s2 && /usr/bin/st key release s1 && /bin/sleep 0.5 && /usr/bin/st key click s1
CMD: /usr/bin/st cap iq af mv 255 -52 255
cur_pos 1507 tar_pos 1455
CMD: /usr/bin/st key push s1 && /bin/sleep 0.3 && /usr/bin/st key click s2 && /usr/bin/st key release s1 && /bin/sleep 0.5 && /usr/bin/st key click s1
CMD: /usr/bin/st app nx capture af-mode single
CMD: /usr/bin/st cap capdtm setusr AFMODE 0x070000
UserData is set
```

**Comment by arspr** [comment]
Well I've tested SAF/CAF/AAF and it always seem to return without a glitch.

A new small issue: Instead of "_**Near/Far focus position set**_" (I've retested v2.00 from nx-patch v5.2 is OK), it says "_**Near/Far ocus position set**_". There's a missing "**f**".

**Comment by arspr** [comment]
Another new issue that I get with focus_stack v2.0 within nx-patch v5.2 but not if I launch v2.2 through telnet. (I mean I don't know if it's a solved issue or if the problem arises with the integration of focus stack inside nx-patch):

- Launch focus stack GUI. (I mean you see the upper toolbar).
- Power the camera off.
- Power the camera on.
- The area previously occupied by the focus tool bar GUI is "empty". I don't see the remaining pictures, battery %, half the battery icon, upper part of grid lines, et cetera. But I see the image from sensor in that area, only the "overlay" text/graphics are affected.
- A battery out cycle fixes the issue.

**Comment by ottokiksmaler** [comment]
Thanks for reporting - invisible frame is bug in gui toolkit used by Samsung, you don't see it when the program is run from SD card since camera kills it on power down. I'll have to detect power off and kill my app as well. 
I really have no idea why it doesn't show notifications on NX1 but I think I have an ugly solution that works. Will try it later on.

**Comment by arspr** [comment]
Another issue with nx-patch: at least on NX1 neither its invocation (LED+LED) nor operating in its menus (touching any option) are recognized as "actions" on the camera so your Auto Display Off and Power Save timers are not reset.

So if my Auto Display Off time is 1 min, and I call nx-patch at 50s I have only 10s before my screen goes out...

If possible, calling nx-patch GUI or operating on any of its menus, submenus or focus stack toolbar should reset power saving countdown timers. (Or for the time being, you could just LOCK power saving countdowns while the nx-patch GUI is shown if it is easier).

**Comment by vasile-gh** [comment]
@ottokiksmaler I will sort it - will kill lingering mod_gui upon power on so don't bother

**Comment by vasile-gh** [comment]
@arspr will try to set auto display off to off during menu operation.

**Comment by ottokiksmaler** [comment]
It's related to focus stack, not mod_gui.

**Comment by vasile-gh** [comment]
@ottokiksmaler for focus_stack, the issue is I plan to disable display off during mod_gui and re-enable to previous values after mod_gui exits. But since focus_stack also require this I am not sure how to proceed since focus_stack runs asynchronously.

**Comment by ottokiksmaler** [comment]
It was related to powering the camera off while focus_stack is running. I have added detecting of power off/on to focus_stack - it now kills itself upon power-on. Also speed improvements. I'm also forcing ELM rendering loop to show notifications on NX1 but not sure if it works.
Here it is
https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/focus_stack?raw=true

**Comment by arspr** [comment]
@ottokiksmaler:

- No luck with the progress indicator in my NX1.
- (About the Power off/on issue. I suppose I cannot test till it's included in nx-patch).
- FIXED. "ocus" typo.
- Not fixed. OK does not still work in configuration window. BTW, both keys are shown in telnet (but not OK on touchscreen):
```
Physical OK: KP_Enter
Touchscreen Intro: Return
```

**Comment by arspr** [comment]
A stupid post: shouldn't this issue report be renamed to v5.x issues?
5.**_1_**x is not true any more.
We are on 5.2 and on the verge of being on 5.3

**Comment by vasile-gh** [comment]
@ottokiksmaler keeping screen and power saving in sync would best work if done in mod_gui (else I need to do an ugly wrapper) because of the way it works with the mod (it is restarted multiple times and not easy to know when it is off "for good". Would be good if you could add this logic to mod_gui: on entry save power savings  settings - 
```
0x0000022c    0004    APPPREF_DISPLAY_SAVE 
0x00000230    0004    APPPREF_POWER_SAVE 
```
and turn them off, and on exit restore them.

**Comment by ottokiksmaler** [comment]
What happens when mod_gui calls another instance?  Or are we past that and we use @ for sub menus? 
Not near the computer right now, but this will be done. To what should we set power and screen save? I don't like the idea that it never goes to sleep while in menu, maybe 5 minutes is plenty? Any ideas?

**Comment by arspr** [comment]
I'd like that every time a menu option (or a focus toolbar button) is pressed, it counted as an "action" in order to reset Samsung stock countdown timers... (if that's possible to achieve)
